//plans
export const CHOOSE_PLAN = 'CHOOSE_PLAN'
export const CREATE_PLAN_REQUEST = 'CREATE_PLAN_REQUEST'
export const CREATE_PLAN_SUCCESS = 'CREATE_PLAN_SUCCESS'
export const FETCH_PLAN_FAILURE = 'FETCH_PLAN_FAILURE'
export const FETCH_PLAN_REQUEST = 'FETCH_PLAN_REQUEST'
export const FETCH_PLAN_SUCCESS = 'FETCH_PLAN_SUCCESS'
export const REMOVE_PLAN_REQUEST = 'REMOVE_PLAN_REQUEST'
export const REMOVE_PLAN_SUCCESS = 'REMOVE_PLAN_SUCCESS'

//posts
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE'
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const PUBLISH_POST_REQUEST = 'PUBLISH_POST_REQUEST'
export const PUBLISH_POST_SUCCESS = 'PUBLISH_POST_SUCCESS'
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'

//providers
export const LINK_ACCOUNT_REQUEST = 'LINK_ACCOUNT_REQUEST'
export const LINK_ACCOUNT_SUCCESS = 'LINK_ACCOUNT_SUCCESS'
export const LOG_IN_WITH_PROVIDER = 'LOG_IN_WITH_PROVIDER'
export const LOG_IN_WITH_PROVIDER_SUCCESS = 'LOG_IN_WITH_PROVIDER_SUCCESS'
export const LOG_IN_WITH_PROVIDER_FAILURE = 'LOG_IN_WITH_PROVIDER_FAILURE'
//what do these do?
export const UPDATE_TOKEN_FAILURE = 'UPDATE_TOKEN_FAILURE'
export const UPDATE_TOKEN_REQUEST = 'UPDATE_TOKEN_REQUEST'
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS'

//users
export const CHECK_USER_TOKEN = 'CHECK_USER_TOKEN'
export const CREATE_USER_WITH_EMAIL = 'CREATE_USER_WITH_EMAIL'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_IMAGE = 'SET_IMAGE'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST'

//miscellaneous
